### PR TITLE
docs: Update README.md

### PR DESCRIPTION
**Pull request by KendallDoesCoding**
Made slight changes to the README.md.

### CODE REVIEW

**Comment by KendallDoesCoding** [comment]
Actually, lemme ask ChatGPT to make a better README.md incorporating my changes as well!

**Comment by TechStudent10** [comment]
IIRC the dev starts on port 5173

**Comment by TechStudent10** [comment]
I'll fix later

**Comment by KendallDoesCoding** [comment]
> IIRC the dev starts on port 5173

oh, that doesn't really matter and it's a slight change!

**Pull request merged**
