### PR TITLE
Update Documentation!

### PR DESCRIPTION
**Pull request by KendallDoesCoding**
I added a "What is Proton Designer" to the Documentation (we can eventually shift it to the main page and not in the docs, this is just temporary) and I deleted the "test1" file.

### CODE REVIEW

**Review by TechStudent10 — APPROVED** [review]
LGTM

**Comment by TechStudent10** [comment]
Please fix the merge conflicts

**Comment by KendallDoesCoding** [comment]
@TechStudent10 - I am unable to resolve conflicts. Even GitHub is saying that the conflicts are too complex to resolve in the web editor. Please advice/help.

**Comment by TechStudent10** [comment]
> @TechStudent10 - I am unable to resolve conflicts. Even GitHub is saying that the conflicts are too complex to resolve in the web editor. Please advice/help.
> 

Don't use the web editor?

**Comment by KendallDoesCoding** [comment]
> > @TechStudent10 - I am unable to resolve conflicts. Even GitHub is saying that the conflicts are too complex to resolve in the web editor. Please advice/help.
> 
> Don't use the web editor?

Yes, I used VS Code, and fixed the issue but when I committed it, the issue didn't get resolved, so idk. It's the blogs that you added that messing this up.


Should I make a new PR?

**Comment by TechStudent10** [comment]
> > > @TechStudent10 - I am unable to resolve conflicts. Even GitHub is saying that the conflicts are too complex to resolve in the web editor. Please advice/help.
> > 
> > Don't use the web editor?
> 
> Yes, I used VS Code, and fixed the issue but when I committed it, the issue didn't get resolved, so idk. It's the blogs that you added that messing this up.
> 
> 
> Should I make a new PR?

Just push your changes ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯

**Comment by KendallDoesCoding** [comment]
Bro, will do it. Reopen the PR.

**Comment by KendallDoesCoding** [comment]
It is saying that the conflicts are too complex to resolve in the web
editor, and then usually it gives a command line method. But, it isn't
giving one.

Can you merge it via the command line please?

*Thanks,*
*Kendall Does Coding*

*Portfolio <https://kendalldoescoding.gq>*
*Github <https://github.com/KendallDoesCoding>*
*Youtube* <https://kendalldoescoding.gq/codingYT>

**Comment by TechStudent10** [comment]
> It is saying that the conflicts are too complex to resolve in the web editor, and then usually it gives a command line method. But, it isn't giving one. Can you merge it via the command line please?

I'm sorry, what? You have to fix the merge conflicts or else everything else breaks. Stop using the web editor if the conflicts are too complex for it, or else I will have to close the PR.

**Comment by KendallDoesCoding** [comment]
Please merge #10

**Pull request closed without merging**
